theme: jekyll-theme-cayman

title: 'PeKo: A Large Scale Precondition Knowledge Dataset'

show_downloads: true
github:
  tar_url: https://drive.google.com/file/d/1FmKcFjKmiT7xWou97xp4nxlNc4UBk8Lq/view?usp=sharing
