theme: jekyll-theme-cayman

title: 'PeKo: A Large Scale Precondition Knowledge Dataset'

tagline: PeKo | PeKo dataset | Precondition knowledge | Precondition dataset | Event precondition

show_downloads: true
github:
  tar_url: https://github.com/StonyBrookNLP/PeKo/blob/main/data/peko_data.tgz

plugins:
  - jekyll-seo-tag
